from flask import Flask, render_template, url_for, redirect, flash, request
from flask_sqlalchemy import SQLAlchemy
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import LoginManager, UserMixin, login_user, login_required, logout_user, current_user

app = Flask(__name__)
app.config['SECRET_KEY'] = 'your-secret-key'
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///your-database.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False  # Disable modification tracking as it is not needed
db = SQLAlchemy(app)
login_manager = LoginManager(app)
login_manager.login_view = 'login'  # Set the login view for redirecting unauthenticated users

class User(UserMixin, db.Model):
        id = db.Column(db.Integer, primary_key=True)
            username = db.Column(db.String(15), unique=True, nullable=False)
                email = db.Column(db.String(50), unique=True, nullable=False)
                    password = db.Column(db.String(80), nullable=False)

                    @login_manager.user_loader
                    def load_user(user_id):
                            return User.query.get(int(user_id))

                        @app.route('/')
                        def home():
                                return render_template('home.html')

                            @app.route('/register', methods=['GET', 'POST'])
                            def register():
                                    if request.method == 'POST':
                                                username = request.form['username']
                                                        email = request.form['email']
                                                                password = request.form['password']

                                                                        # Validate input (e.g., check for existing username or email)

                                                                                hashed_password = generate_password_hash(password, method='sha256')
                                                                                        new_user = User(username=username, email=email, password=hashed_password)

                                                                                                try:
                                                                                                                db.session.add(new_user)
                                                                                                                            db.session.commit()
                                                                                                                                        flash('Account created successfully. You can now log in.', 'success')
                                                                                                                                                    return redirect(url_for('login'))
                                                                                                                                                        except Exception as e:
                                                                                                                                                                        db.session.rollback()
                                                                                                                                                                                    flash(f'Error creating account: {str(e)}', 'danger')

                                                                                                                                                                                        return render_template('register.html')

                                                                                                                                                                                    @app.route('/login', methods=['GET', 'POST'])
                                                                                                                                                                                    def login():
                                                                                                                                                                                            if request.method == 'POST':
                                                                                                                                                                                                        username = request.form['username']
                                                                                                                                                                                                                password = request.form['password']

                                                                                                                                                                                                                        user = User.query.filter_by(username=username).first()

                                                                                                                                                                                                                                if user and check_password_hash(user.password, password):
                                                                                                                                                                                                                                                login_user(user, remember=True)
                                                                                                                                                                                                                                                            return redirect(url_for('home'))

                                                                                                                                                                                                                                                                flash('Login unsuccessful. Please check your username and password.', 'danger')

                                                                                                                                                                                                                                                                    return render_template('login.html')

                                                                                                                                                                                                                                                                @app.route('/logout')
                                                                                                                                                                                                                                                                @login_required
                                                                                                                                                                                                                                                                def logout():
                                                                                                                                                                                                                                                                        logout_user()
                                                                                                                                                                                                                                                                            flash('You have been logged out.', 'info')
                                                                                                                                                                                                                                                                                return redirect(url_for('home'))

                                                                                                                                                                                                                                                                            if __name__ == '__main__':
                                                                                                                                                                                                                                                                                    db.create_all()  # Create tables before running the app
                                                                                                                                                                                                                                                                                        app.run(debug=True)
                                                                                                                                                                                                                                                                                        from flask import Flask, render_template, url_for, redirect, flash, request
                                                                                                                                                                                                                                                                                        from flask_sqlalchemy import SQLAlchemy
                                                                                                                                                                                                                                                                                        from werkzeug.security import generate_password_hash, check_password_hash
                                                                                                                                                                                                                                                                                        from flask_login import LoginManager, UserMixin, login_user, login_required, logout_user, current_user

                                                                                                                                                                                                                                                                                        app = Flask(__name__)
                                                                                                                                                                                                                                                                                        app.config['SECRET_KEY'] = 'your-secret-key'
                                                                                                                                                                                                                                                                                        app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///your-database.db'
                                                                                                                                                                                                                                                                                        app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False  # Disable modification tracking as it is not needed
                                                                                                                                                                                                                                                                                        db = SQLAlchemy(app)
                                                                                                                                                                                                                                                                                        login_manager = LoginManager(app)
                                                                                                                                                                                                                                                                                        login_manager.login_view = 'login'  # Set the login view for redirecting unauthenticated users

                                                                                                                                                                                                                                                                                        class User(UserMixin, db.Model):
                                                                                                                                                                                                                                                                                                id = db.Column(db.Integer, primary_key=True)
                                                                                                                                                                                                                                                                                                    username = db.Column(db.String(15), unique=True, nullable=False)
                                                                                                                                                                                                                                                                                                        email = db.Column(db.String(50), unique=True, nullable=False)
                                                                                                                                                                                                                                                                                                            password = db.Column(db.String(80), nullable=False)

                                                                                                                                                                                                                                                                                                            @login_manager.user_loader
                                                                                                                                                                                                                                                                                                            def load_user(user_id):
                                                                                                                                                                                                                                                                                                                    return User.query.get(int(user_id))

                                                                                                                                                                                                                                                                                                                @app.route('/')
                                                                                                                                                                                                                                                                                                                def home():
                                                                                                                                                                                                                                                                                                                        return render_template('home.html')

                                                                                                                                                                                                                                                                                                                    @app.route('/register', methods=['GET', 'POST'])
                                                                                                                                                                                                                                                                                                                    def register():
                                                                                                                                                                                                                                                                                                                            if request.method == 'POST':
                                                                                                                                                                                                                                                                                                                                        username = request.form['username']
                                                                                                                                                                                                                                                                                                                                                email = request.form['email']
                                                                                                                                                                                                                                                                                                                                                        password = request.form['password']

                                                                                                                                                                                                                                                                                                                                                                # Validate input (e.g., check for existing username or email)

                                                                                                                                                                                                                                                                                                                                                                        hashed_password = generate_password_hash(password, method='sha256')
                                                                                                                                                                                                                                                                                                                                                                                new_user = User(username=username, email=email, password=hashed_password)

                                                                                                                                                                                                                                                                                                                                                                                        try:
                                                                                                                                                                                                                                                                                                                                                                                                        db.session.add(new_user)
                                                                                                                                                                                                                                                                                                                                                                                                                    db.session.commit()
                                                                                                                                                                                                                                                                                                                                                                                                                                flash('Account created successfully. You can now log in.', 'success')
                                                                                                                                                                                                                                                                                                                                                                                                                                            return redirect(url_for('login'))
                                                                                                                                                                                                                                                                                                                                                                                                                                                except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                db.session.rollback()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            flash(f'Error creating account: {str(e)}', 'danger')

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return render_template('register.html')

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @app.route('/login', methods=['GET', 'POST'])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def login():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if request.method == 'POST':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                username = request.form['username']
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        password = request.form['password']

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                user = User.query.filter_by(username=username).first()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if user and check_password_hash(user.password, password):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        login_user(user, remember=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return redirect(url_for('home'))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        flash('Login unsuccessful. Please check your username and password.', 'danger')

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return render_template('login.html')

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @app.route('/logout')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @login_required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def logout():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                logout_user()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    flash('You have been logged out.', 'info')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return redirect(url_for('home'))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if __name__ == '__main__':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            db.create_all()  # Create tables before running the app
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                app.run(debug=True)

